# Donate to Dash Eclipse (callsmusic/tgvc-userbot)
# bitcoin:bc1q0zflkafncpxy87rc7tcx23v7tdtu0vkxe2dyap?message=Donate%20to%20Dash%20Eclipse%20%28callsmusic%2Ftgvc-userbot%29
custom: ["https://github.com/callsmusic/tgvc-userbot/blob/dev/.github/FUNDING.yml"]
